id: I9C810110
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T11:54:08+00:00'
last_modified: '2022-06-08T04:46:52.573180+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W127
  title: གསུང་ཐོར་བུ། ཤེས་རབ་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    565B:
      image_group_id: I1CZ986
      title: ''
      total_pages: 294
      order: 1
      base_file: 565B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
