id: P005540
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:58:21.190372
source_metadata:
  id: bdr:W127
  title: གསུང་ཐོར་བུ། ཤེས་རབ་རྒྱ་མཚོ
  author: ''
  volumes:
    17a580a75ccc44d7aff9f76ab11cd05c:
      image_group_id: I1CZ986
      title: ''
      volume_number: 1
      total_pages: 294
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
